services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      network: host
    user: app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/:/workspace
    working_dir: /workspace
    env_file:
      - ./server/.env
    entrypoint: "/app/target/release/app start-server"
    depends_on:
      - postgres
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    user: root
    entrypoint: ["nginx", "-g", "daemon off;"]
    depends_on:
      - server
  postgres:
    image: postgres:latest
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    volumes:
      - ./server/:/workspace
    working_dir: /workspace
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

