[package]
name = "web-app"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
registry.workspace = true
shared.workspace = true
serde.workspace = true
tracing.workspace = true
